spring:
  application:
    name: spring-security-oauth2-server
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    jdbc-url: jdbc:mysql://localhost:3306/oauth2?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT&useSSL=false
    username: root
    password: root
server:
  port: 8080

mybatis-plus:
  mapper-locations: classpath:/mybatis/mapper/*.xml
  type-aliases-package: com.li.entity
  configuration:
    #开启驼峰命名的转换
    map-underscore-to-camel-case: true